export enum Permission {
  POST_CREATE = 'POST_CREATE',
  POST_EDIT_OWN = 'POST_EDIT_OWN',
  POST_EDIT_ANY = 'POST_EDIT_ANY',
  POST_DELETE = 'POST_DELETE',
  POST_PUBLISH = 'POST_PUBLISH',
  POST_VIEW_DRAFTS = 'POST_VIEW_DRAFTS',
  USER_ROLE_MANAGE = 'USER_ROLE_MANAGE'
}
